using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using LitJson;

namespace PokeAPI.NET
{
    /// <summary>
    /// Represents an instance of a Pokémon Move
    /// </summary>
    public class PokeMove : PokeApiType
    {
        /// <summary>
        /// Wether it should cache moves or not
        /// </summary>
        public static bool ShouldCacheData = true;
        /// <summary>
        /// Gets all cached moves
        /// </summary>
        public static Dictionary<int, PokeMove> CachedMoves = new Dictionary<int, PokeMove>();

        #region public readonly static Dictionary<string, int> IDs = new Dictionary<string, int> { [...] };
        /// <summary>
        /// All move string->ID maps
        /// </summary>
        public readonly static Dictionary<string, int> IDs = new Dictionary<string, int>
        {
            {"Pound", 1},
            {"Karate chop", 2},
            {"Doubleslap", 3},
            {"Comet punch", 4},
            {"Mega punch", 5},
            {"Pay day", 6},
            {"Fire punch", 7},
            {"Ice punch", 8},
            {"Thunderpunch", 9},
            {"Scratch", 10},
            {"Vicegrip", 11},
            {"Guillotine", 12},
            {"Razor wind", 13},
            {"Swords dance", 14},
            {"Cut", 15},
            {"Gust", 16},
            {"Wing attack", 17},
            {"Whirlwind", 18},
            {"Fly", 19},
            {"Bind", 20},
            {"Slam", 21},
            {"Vine whip", 22},
            {"Stomp", 23},
            {"Double kick", 24},
            {"Mega kick", 25},
            {"Jump kick", 26},
            {"Rolling kick", 27},
            {"Sand attack", 28},
            {"Headbutt", 29},
            {"Horn attack", 30},
            {"Fury attack", 31},
            {"Horn drill", 32},
            {"Tackle", 33},
            {"Body slam", 34},
            {"Wrap", 35},
            {"Take down", 36},
            {"Thrash", 37},
            {"Double edge", 38},
            {"Tail whip", 39},
            {"Poison sting", 40},
            {"Twineedle", 41},
            {"Pin missile", 42},
            {"Leer", 43},
            {"Bite", 44},
            {"Growl", 45},
            {"Roar", 46},
            {"Sing", 47},
            {"Supersonic", 48},
            {"Sonicboom", 49},
            {"Disable", 50},
            {"Acid", 51},
            {"Ember", 52},
            {"Flamethrower", 53},
            {"Mist", 54},
            {"Water gun", 55},
            {"Hydro pump", 56},
            {"Surf", 57},
            {"Ice beam", 58},
            {"Blizzard", 59},
            {"Psybeam", 60},
            {"Bubblebeam", 61},
            {"Aurora beam", 62},
            {"Hyper beam", 63},
            {"Peck", 64},
            {"Drill peck", 65},
            {"Submission", 66},
            {"Low kick", 67},
            {"Counter", 68},
            {"Seismic toss", 69},
            {"Strength", 70},
            {"Absorb", 71},
            {"Mega drain", 72},
            {"Leech seed", 73},
            {"Growth", 74},
            {"Razor leaf", 75},
            {"Solarbeam", 76},
            {"Poisonpowder", 77},
            {"Stun spore", 78},
            {"Sleep powder", 79},
            {"Petal dance", 80},
            {"String shot", 81},
            {"Dragon rage", 82},
            {"Fire spin", 83},
            {"Thundershock", 84},
            {"Thunderbolt", 85},
            {"Thunder wave", 86},
            {"Thunder", 87},
            {"Rock throw", 88},
            {"Earthquake", 89},
            {"Fissure", 90},
            {"Dig", 91},
            {"Toxic", 92},
            {"Confusion", 93},
            {"Psychic", 94},
            {"Hypnosis", 95},
            {"Meditate", 96},
            {"Agility", 97},
            {"Quick attack", 98},
            {"Rage", 99},
            {"Teleport", 100},
            {"Night shade", 101},
            {"Mimic", 102},
            {"Screech", 103},
            {"Double team", 104},
            {"Recover", 105},
            {"Harden", 106},
            {"Minimize", 107},
            {"Smokescreen", 108},
            {"Confuse ray", 109},
            {"Withdraw", 110},
            {"Defense curl", 111},
            {"Barrier", 112},
            {"Light screen", 113},
            {"Haze", 114},
            {"Reflect", 115},
            {"Focus energy", 116},
            {"Bide", 117},
            {"Metronome", 118},
            {"Mirror move", 119},
            {"Selfdestruct", 120},
            {"Egg bomb", 121},
            {"Lick", 122},
            {"Smog", 123},
            {"Sludge", 124},
            {"Bone club", 125},
            {"Fire blast", 126},
            {"Waterfall", 127},
            {"Clamp", 128},
            {"Swift", 129},
            {"Skull bash", 130},
            {"Spike cannon", 131},
            {"Constrict", 132},
            {"Amnesia", 133},
            {"Kinesis", 134},
            {"Softboiled", 135},
            {"Hi jump kick", 136},
            {"Glare", 137},
            {"Dream eater", 138},
            {"Poison gas", 139},
            {"Barrage", 140},
            {"Leech life", 141},
            {"Lovely kiss", 142},
            {"Sky attack", 143},
            {"Transform", 144},
            {"Bubble", 145},
            {"Dizzy punch", 146},
            {"Spore", 147},
            {"Flash", 148},
            {"Psywave", 149},
            {"Splash", 150},
            {"Acid armor", 151},
            {"Crabhammer", 152},
            {"Explosion", 153},
            {"Fury swipes", 154},
            {"Bonemerang", 155},
            {"Rest", 156},
            {"Rock slide", 157},
            {"Hyper fang", 158},
            {"Sharpen", 159},
            {"Conversion", 160},
            {"Tri attack", 161},
            {"Super fang", 162},
            {"Slash", 163},
            {"Substitute", 164},
            {"Struggle", 165},
            {"Sketch", 166},
            {"Triple kick", 167},
            {"Thief", 168},
            {"Spider web", 169},
            {"Mind reader", 170},
            {"Nightmare", 171},
            {"Flame wheel", 172},
            {"Snore", 173},
            {"Curse", 174},
            {"Flail", 175},
            {"Conversion 2", 176},
            {"Aeroblast", 177},
            {"Cotton spore", 178},
            {"Reversal", 179},
            {"Spite", 180},
            {"Powder snow", 181},
            {"Protect", 182},
            {"Mach punch", 183},
            {"Scary face", 184},
            {"Faint attack", 185},
            {"Sweet kiss", 186},
            {"Belly drum", 187},
            {"Sludge bomb", 188},
            {"Mud slap", 189},
            {"Octazooka", 190},
            {"Spikes", 191},
            {"Zap cannon", 192},
            {"Foresight", 193},
            {"Destiny bond", 194},
            {"Perish song", 195},
            {"Icy wind", 196},
            {"Detect", 197},
            {"Bone rush", 198},
            {"Lock on", 199},
            {"Outrage", 200},
            {"Sandstorm", 201},
            {"Giga drain", 202},
            {"Endure", 203},
            {"Charm", 204},
            {"Rollout", 205},
            {"False swipe", 206},
            {"Swagger", 207},
            {"Milk drink", 208},
            {"Spark", 209},
            {"Fury cutter", 210},
            {"Steel wing", 211},
            {"Mean look", 212},
            {"Attract", 213},
            {"Sleep talk", 214},
            {"Heal bell", 215},
            {"Return", 216},
            {"Present", 217},
            {"Frustration", 218},
            {"Safeguard", 219},
            {"Pain split", 220},
            {"Sacred fire", 221},
            {"Magnitude", 222},
            {"Dynamicpunch", 223},
            {"Megahorn", 224},
            {"Dragonbreath", 225},
            {"Baton pass", 226},
            {"Encore", 227},
            {"Pursuit", 228},
            {"Rapid spin", 229},
            {"Sweet scent", 230},
            {"Iron tail", 231},
            {"Metal claw", 232},
            {"Vital throw", 233},
            {"Morning sun", 234},
            {"Synthesis", 235},
            {"Moonlight", 236},
            {"Hidden power", 237},
            {"Cross chop", 238},
            {"Twister", 239},
            {"Rain dance", 240},
            {"Sunny day", 241},
            {"Crunch", 242},
            {"Mirror coat", 243},
            {"Psych up", 244},
            {"Extremespeed", 245},
            {"Ancientpower", 246},
            {"Shadow ball", 247},
            {"Future sight", 248},
            {"Rock smash", 249},
            {"Whirlpool", 250},
            {"Beat up", 251},
            {"Fake out", 252},
            {"Uproar", 253},
            {"Stockpile", 254},
            {"Spit up", 255},
            {"Swallow", 256},
            {"Heat wave", 257},
            {"Hail", 258},
            {"Torment", 259},
            {"Flatter", 260},
            {"Will o wisp", 261},
            {"Memento", 262},
            {"Facade", 263},
            {"Focus punch", 264},
            {"Smellingsalt", 265},
            {"Follow me", 266},
            {"Nature power", 267},
            {"Charge", 268},
            {"Taunt", 269},
            {"Helping hand", 270},
            {"Trick", 271},
            {"Role play", 272},
            {"Wish", 273},
            {"Assist", 274},
            {"Ingrain", 275},
            {"Superpower", 276},
            {"Magic coat", 277},
            {"Recycle", 278},
            {"Revenge", 279},
            {"Brick break", 280},
            {"Yawn", 281},
            {"Knock off", 282},
            {"Endeavor", 283},
            {"Eruption", 284},
            {"Skill swap", 285},
            {"Imprison", 286},
            {"Refresh", 287},
            {"Grudge", 288},
            {"Snatch", 289},
            {"Secret power", 290},
            {"Dive", 291},
            {"Arm thrust", 292},
            {"Camouflage", 293},
            {"Tail glow", 294},
            {"Luster purge", 295},
            {"Mist ball", 296},
            {"Featherdance", 297},
            {"Teeter dance", 298},
            {"Blaze kick", 299},
            {"Mud sport", 300},
            {"Ice ball", 301},
            {"Needle arm", 302},
            {"Slack off", 303},
            {"Hyper voice", 304},
            {"Poison fang", 305},
            {"Crush claw", 306},
            {"Blast burn", 307},
            {"Hydro cannon", 308},
            {"Meteor mash", 309},
            {"Astonish", 310},
            {"Weather ball", 311},
            {"Aromatherapy", 312},
            {"Fake tears", 313},
            {"Air cutter", 314},
            {"Overheat", 315},
            {"Odor sleuth", 316},
            {"Rock tomb", 317},
            {"Silver wind", 318},
            {"Metal sound", 319},
            {"Grasswhistle", 320},
            {"Tickle", 321},
            {"Cosmic power", 322},
            {"Water spout", 323},
            {"Signal beam", 324},
            {"Shadow punch", 325},
            {"Extrasensory", 326},
            {"Sky uppercut", 327},
            {"Sand tomb", 328},
            {"Sheer cold", 329},
            {"Muddy water", 330},
            {"Bullet seed", 331},
            {"Aerial ace", 332},
            {"Icicle spear", 333},
            {"Iron defense", 334},
            {"Block", 335},
            {"Howl", 336},
            {"Dragon claw", 337},
            {"Frenzy plant", 338},
            {"Bulk up", 339},
            {"Bounce", 340},
            {"Mud shot", 341},
            {"Poison tail", 342},
            {"Covet", 343},
            {"Volt tackle", 344},
            {"Magical leaf", 345},
            {"Water sport", 346},
            {"Calm mind", 347},
            {"Leaf blade", 348},
            {"Dragon dance", 349},
            {"Rock blast", 350},
            {"Shock wave", 351},
            {"Water pulse", 352},
            {"Doom desire", 353},
            {"Psycho boost", 354},
            {"Roost", 355},
            {"Gravity", 356},
            {"Miracle eye", 357},
            {"Wake up slap", 358},
            {"Hammer arm", 359},
            {"Gyro ball", 360},
            {"Healing wish", 361},
            {"Brine", 362},
            {"Natural gift", 363},
            {"Feint", 364},
            {"Pluck", 365},
            {"Tailwind", 366},
            {"Acupressure", 367},
            {"Metal burst", 368},
            {"U turn", 369},
            {"Close combat", 370},
            {"Payback", 371},
            {"Assurance", 372},
            {"Embargo", 373},
            {"Fling", 374},
            {"Psycho shift", 375},
            {"Trump card", 376},
            {"Heal block", 377},
            {"Wring out", 378},
            {"Power trick", 379},
            {"Gastro acid", 380},
            {"Lucky chant", 381},
            {"Me first", 382},
            {"Copycat", 383},
            {"Power swap", 384},
            {"Guard swap", 385},
            {"Punishment", 386},
            {"Last resort", 387},
            {"Worry seed", 388},
            {"Sucker punch", 389},
            {"Toxic spikes", 390},
            {"Heart swap", 391},
            {"Aqua ring", 392},
            {"Magnet rise", 393},
            {"Flare blitz", 394},
            {"Force palm", 395},
            {"Aura sphere", 396},
            {"Rock polish", 397},
            {"Poison jab", 398},
            {"Dark pulse", 399},
            {"Night slash", 400},
            {"Aqua tail", 401},
            {"Seed bomb", 402},
            {"Air slash", 403},
            {"X scissor", 404},
            {"Bug buzz", 405},
            {"Dragon pulse", 406},
            {"Dragon rush", 407},
            {"Power gem", 408},
            {"Drain punch", 409},
            {"Vacuum wave", 410},
            {"Focus blast", 411},
            {"Energy ball", 412},
            {"Brave bird", 413},
            {"Earth power", 414},
            {"Switcheroo", 415},
            {"Giga impact", 416},
            {"Nasty plot", 417},
            {"Bullet punch", 418},
            {"Avalanche", 419},
            {"Ice shard", 420},
            {"Shadow claw", 421},
            {"Thunder fang", 422},
            {"Ice fang", 423},
            {"Fire fang", 424},
            {"Shadow sneak", 425},
            {"Mud bomb", 426},
            {"Psycho cut", 427},
            {"Zen headbutt", 428},
            {"Mirror shot", 429},
            {"Flash cannon", 430},
            {"Rock climb", 431},
            {"Defog", 432},
            {"Trick room", 433},
            {"Draco meteor", 434},
            {"Discharge", 435},
            {"Lava plume", 436},
            {"Leaf storm", 437},
            {"Power whip", 438},
            {"Rock wrecker", 439},
            {"Cross poison", 440},
            {"Gunk shot", 441},
            {"Iron head", 442},
            {"Magnet bomb", 443},
            {"Stone edge", 444},
            {"Captivate", 445},
            {"Stealth rock", 446},
            {"Grass knot", 447},
            {"Chatter", 448},
            {"Judgment", 449},
            {"Bug bite", 450},
            {"Charge beam", 451},
            {"Wood hammer", 452},
            {"Aqua jet", 453},
            {"Attack order", 454},
            {"Defend order", 455},
            {"Heal order", 456},
            {"Head smash", 457},
            {"Double hit", 458},
            {"Roar of time", 459},
            {"Spacial rend", 460},
            {"Lunar dance", 461},
            {"Crush grip", 462},
            {"Magma storm", 463},
            {"Dark void", 464},
            {"Seed flare", 465},
            {"Ominous wind", 466},
            {"Shadow force", 467},
            {"Hone claws", 468},
            {"Wide guard", 469},
            {"Guard split", 470},
            {"Power split", 471},
            {"Wonder room", 472},
            {"Psyshock", 473},
            {"Venoshock", 474},
            {"Autotomize", 475},
            {"Rage powder", 476},
            {"Telekinesis", 477},
            {"Magic room", 478},
            {"Smack down", 479},
            {"Storm throw", 480},
            {"Flame burst", 481},
            {"Sludge wave", 482},
            {"Quiver dance", 483},
            {"Heavy slam", 484},
            {"Synchronoise", 485},
            {"Electro ball", 486},
            {"Soak", 487},
            {"Flame charge", 488},
            {"Coil", 489},
            {"Low sweep", 490},
            {"Acid spray", 491},
            {"Foul play", 492},
            {"Simple beam", 493},
            {"Entrainment", 494},
            {"After you", 495},
            {"Round", 496},
            {"Echoed voice", 497},
            {"Chip away", 498},
            {"Clear smog", 499},
            {"Stored power", 500},
            {"Quick guard", 501},
            {"Ally switch", 502},
            {"Scald", 503},
            {"Shell smash", 504},
            {"Heal pulse", 505},
            {"Hex", 506},
            {"Sky drop", 507},
            {"Shift gear", 508},
            {"Circle throw", 509},
            {"Incinerate", 510},
            {"Quash", 511},
            {"Acrobatics", 512},
            {"Reflect type", 513},
            {"Retaliate", 514},
            {"Final gambit", 515},
            {"Bestow", 516},
            {"Inferno", 517},
            {"Water pledge", 518},
            {"Fire pledge", 519},
            {"Grass pledge", 520},
            {"Volt switch", 521},
            {"Struggle bug", 522},
            {"Bulldoze", 523},
            {"Frost breath", 524},
            {"Dragon tail", 525},
            {"Work up", 526},
            {"Electroweb", 527},
            {"Wild charge", 528},
            {"Drill run", 529},
            {"Dual chop", 530},
            {"Heart stamp", 531},
            {"Horn leech", 532},
            {"Sacred sword", 533},
            {"Razor shell", 534},
            {"Heat crash", 535},
            {"Leaf tornado", 536},
            {"Steamroller", 537},
            {"Cotton guard", 538},
            {"Night daze", 539},
            {"Psystrike", 540},
            {"Tail slap", 541},
            {"Hurricane", 542},
            {"Head charge", 543},
            {"Gear grind", 544},
            {"Searing shot", 545},
            {"Techno blast", 546},
            {"Relic song", 547},
            {"Secret sword", 548},
            {"Glaciate", 549},
            {"Bolt strike", 550},
            {"Blue flare", 551},
            {"Fiery dance", 552},
            {"Freeze shock", 553},
            {"Ice burn", 554},
            {"Snarl", 555},
            {"Icicle crash", 556},
            {"V create", 557},
            {"Fusion flare", 558},
            {"Fusion bolt", 559},
            {"Baby doll eyes", 560},
            {"Belch", 561},
            {"Boomburst", 562},
            {"Confide", 563},
            {"Crafty shield", 564},
            {"Dazzling gleam", 565},
            {"Disarming voice", 566},
            {"Draining kiss", 567},
            {"Eerie impulse", 568},
            {"Electric terrain", 569},
            {"Electrify", 570},
            {"Fairy lock", 571},
            {"Fairy wind", 572},
            {"Fell stinger", 573},
            {"Flower shield", 574},
            {"Flying press", 575},
            {"Forests curse", 576},
            {"Freeze dry", 577},
            {"Geomancy", 578},
            {"Grassy terrain", 579},
            {"Infestation", 580},
            {"Ion deluge", 581},
            {"Kings shield", 582},
            {"Lands wrath", 583},
            {"Magnetic flux", 584},
            {"Mat block", 585},
            {"Misty terrain", 586},
            {"Moonblast", 587},
            {"Mystical fire", 588},
            {"Noble roar", 589},
            {"Nuzzle", 590},
            {"Oblivion wing", 591},
            {"Parabolic charge", 592},
            {"Parting shot", 593},
            {"Petal blizzard", 594},
            {"Phantom force", 595},
            {"Play nice", 596},
            {"Play rough", 597},
            {"Powder", 598},
            {"Power up punch", 599},
            {"Rototiller", 600},
            {"Spiky shield", 601},
            {"Sticky web", 602},
            {"Topsy turvy", 603},
            {"Trick or treat", 604},
            {"Venom drench", 605},
            {"Water shuriken", 606},
            {"Aromatic mist", 607},
            {"Shadow rush", 608},
            {"Shadow blast", 609},
            {"Shadow blitz", 610},
            {"Shadow bolt", 611},
            {"Shadow break", 612},
            {"Shadow chill", 613},
            {"Shadow end", 614},
            {"Shadow fire", 615},
            {"Shadow rave", 616},
            {"Shadow storm", 617},
            {"Shadow wave", 618},
            {"Shadow down", 619},
            {"Shadow half", 620},
            {"Shadow hold", 621},
            {"Shadow mist", 622},
            {"Shadow panic", 623},
            {"Shadow shed", 624},
            {"Shadow sky", 625}
        };
        #endregion

        string description;
        int power, pp;
        double accuracy;
        MoveCategory category;

        /// <summary>
        /// A description of the PokeMove instance
        /// </summary>
        public string Description
        {
            get
            {
                return description;
            }
        }
        /// <summary>
        /// The base power of the PokeMove instance
        /// </summary>
        public int Power
        {
            get
            {
                return power;
            }
        }
        /// <summary>
        /// The base power points of the PokeMove instance
        /// </summary>
        public int PP
        {
            get
            {
                return pp;
            }
        }
        /// <summary>
        /// The base accuracy of the PokeMove instance
        /// </summary>
        public double Accurracy
        {
            get
            {
                return accuracy;
            }
        }
        /// <summary>
        /// The category of the PokeMove instance
        /// </summary>
        public MoveCategory Category
        {
            get
            {
                return category;
            }
        }

        /// <summary>
        /// Creates a new instance from a JSON object
        /// </summary>
        /// <param name="source">The JSON object where to create the new instance from</param>
        protected override void Create(JsonData source)
        {
            description = source["description"].ToString();
            power = (int)source["power"];
            pp = (int)source["pp"];
            accuracy = Convert.ToDouble(source["accuracy"].ToString(), CultureInfo.InvariantCulture) / 100d;
            MoveCategory cat = 0;
            Enum.TryParse(source["category"].ToString(), true, out cat);
            category = cat;

            if (ShouldCacheData && !CachedMoves.ContainsKey(ID))
                CachedMoves.Add(ID, this);
        }

        /// <summary>
        /// Creates an instance of a PokeMove with the given name
        /// </summary>
        /// <param name="name">The name of the PokeMove to instantiate</param>
        /// <returns>The created instance of the PokeMove</returns>
        public static PokeMove GetInstance(string name)
        {
            return GetInstance(IDs[name]);
        }
        /// <summary>
        /// Creates an instance of a PokeMove with the given ID
        /// </summary>
        /// <param name="id">The id of the PokeMove to instantiate</param>
        /// <returns>The created instance of the PokeMove</returns>
        public static PokeMove GetInstance(int id)
        {
            if (CachedMoves.ContainsKey(id))
                return CachedMoves[id];

            PokeMove p = new PokeMove();
            Create(DataFetcher.GetMove(id), p);

            if (ShouldCacheData)
                CachedMoves.Add(id, p);

            return p;
        }
    }
}
